In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns

import gc

from datetime import datetime

In [2]:
pd.set_option('max_rows', 2000)

In [3]:
def transform_date(df):
    df['day'] =  pd.DatetimeIndex(df['click_time']).day
    df['weekday'] = pd.DatetimeIndex(df['click_time']).weekday
    df['hour'] = pd.DatetimeIndex(df['click_time']).hour
    df['minutes'] = pd.DatetimeIndex(df['click_time']).minute
    df['seconds'] = pd.DatetimeIndex(df['click_time']).second
    return df

In [4]:
test = pd.read_csv('/Users/mengruiyin/Dropbox/project3/test.csv')

In [5]:
test = transform_date(test)

In [6]:
sample_train = pd.read_csv('sample_train_new.csv')

Due to large size of the data, I cannot use all the data. So I selected data who have the same click hour as the test data. The test data have click hours 14, 15,  4,  5,  6,  9, 10, 11, 12, 13. So we selected data from train set which have these click hours.

In [7]:
sample_train['set'] = 'train'

In [8]:
test['set'] = 'test'

In order to create features, I combined train data and test data which were provided by talkingdata together.

* original features: ip, app, device, os, channel
* click_time feature: day, weekday, hour, minutes, seconds
* count features: 
    * ip 
    * app
    * os
    * channel
    * ip, app
    * ip, device
    * ip, os
    * app, device
    * app, channel
    * app, os
    * ip, device, app
    * ip, device, os
    * ip, os, channel
    * ip, app, channel
* nunique-count feature
    * ip [app]
    * ip [device]
    * ip [os]
    * ip [channel]
    * app [os]
    * app [channel]
    * ip, app [os]
    * ip, app [device]
    * ip, device, os [app]
    * ip, day [hour]
* previous_click_time
    * day ip device os/first time
    * day ip device os app/first time
 
* total 38 features

In [ ]:
'ip', 'app', 'device', 'os', 'channel', 'day', 'weekday',
       'hour', 'minutes', 'seconds', 'ip_count', 'app_count', 'os_count',
       'channel_count', 'ipapp_count', 'ipdevice_count', 'ipos_count',
       'appdevice_count', 'appchannel_count', 'appos_count', 'ida_count',
       'ido_count', 'ioc_count', 'iac_count', 'ido_pct', 'didoa_pct',
       'dido_first', 'didoa_first', 'napp_byip', 'ndevice_byip', 'nos_byip',
       'nchannel_byip', 'nos_byapp', 'nchannel_byapp', 'nos_byipapp',
       'ndevice_byipapp', 'napp_byido', 'nhour_byipday'

In [9]:
sample_train2 = sample_train[['ip', 'app', 'device', 'os', 'channel', 'click_time', 'day', 'weekday', 'hour', 'minutes', 'seconds', 'set']]

In [10]:
sample_train2.shape

(99332659, 12)

In [11]:
test = test[['ip', 'app', 'device', 'os', 'channel', 'click_time', 'day', 'weekday', 'hour', 'minutes', 'seconds', 'set']]

In [12]:
test.shape

(18790469, 12)

In [13]:
full_data = pd.concat([sample_train2, test], axis = 0)

In [14]:
full_data.shape

(118123128, 12)

In [15]:
full_data.dtypes

ip             int64
app            int64
device         int64
os             int64
channel        int64
click_time    object
day            int64
weekday        int64
hour           int64
minutes        int64
seconds        int64
set           object
dtype: object

In [16]:
sample_train.day.unique()

array([6, 7, 8, 9])

In [17]:
del sample_train, test

In [18]:
del sample_train2

In [19]:
gc.collect()

28

In [20]:
variables = ['ip', 'app', 'device', 'os', 'channel']
for item in variables:
    full_data[item] = full_data[item].astype('category')

In [21]:
full_data.dtypes

ip            category
app           category
device        category
os            category
channel       category
click_time      object
day              int64
weekday          int64
hour             int64
minutes          int64
seconds          int64
set             object
dtype: object

In [22]:
full_data.shape

(118123128, 12)

count feature
* ip, app, os, channel
* ip, app
* ip, device
* ip, os
* app, device
* app, channel
* app, os
* ip, device, app
* ip, device, os
* ip, os, channel
* ip, app, channel
* ip, device, os, app, channel

### count features

In [23]:
full_data['ip_count'] = full_data.groupby(['ip'])['click_time'].transform('count')

In [24]:
full_data['app_count'] = full_data.groupby(['app'])['click_time'].transform('count')

In [25]:
full_data['os_count'] = full_data.groupby(['os'])['click_time'].transform('count')

In [26]:
full_data['channel_count'] = full_data.groupby(['channel'])['click_time'].transform('count')

In [27]:
full_data['ipapp_count'] = full_data.groupby(['ip', 'app'])['click_time'].transform('count')

In [28]:
full_data['ipdevice_count'] = full_data.groupby(['ip', 'device'])['click_time'].transform('count')

In [29]:
full_data['ipos_count'] = full_data.groupby(['ip', 'os'])['click_time'].transform('count')

In [30]:
full_data['appdevice_count'] = full_data.groupby(['app', 'device'])['click_time'].transform('count')

In [31]:
full_data['appchannel_count'] = full_data.groupby(['app', 'channel'])['click_time'].transform('count')

In [32]:
full_data['appos_count'] = full_data.groupby(['app', 'os'])['click_time'].transform('count')

In [33]:
# full_data.to_csv('full_data_0702.csv', index = False)

In [2]:
full_data = pd.read_csv('full_data_0702.csv')

In [3]:
full_data['ida_count'] = full_data.groupby(['ip', 'device', 'app'])['click_time'].transform('count')

In [4]:
full_data['ido_count'] = full_data.groupby(['ip', 'device', 'os'])['click_time'].transform('count')

In [6]:
full_data['ioc_count'] = full_data.groupby(['ip', 'os', 'channel'])['click_time'].transform('count')

In [7]:
# full_data.to_csv('full_data_0702_version2.csv', index = False)

In [2]:
full_data = pd.read_csv('full_data_0702_version2.csv')

In [3]:
full_data['iac_count'] = full_data.groupby(['ip', 'app', 'channel'])['click_time'].transform('count')

In [5]:
full_data.to_csv('full_data_0702.csv', index = False)

In [ ]:
full_data['idoac_count'] = full_data.groupby(['ip', 'device', 'os', 'app', 'channel'])['click_time'].transform('count')

In [6]:
full_data.shape

(118123128, 26)

In [7]:
gc.collect()

0

In [8]:
full_data.columns

Index(['ip', 'app', 'device', 'os', 'channel', 'click_time', 'day', 'weekday',
       'hour', 'minutes', 'seconds', 'set', 'ip_count', 'app_count',
       'os_count', 'channel_count', 'ipapp_count', 'ipdevice_count',
       'ipos_count', 'appdevice_count', 'appchannel_count', 'appos_count',
       'ida_count', 'ido_count', 'ioc_count', 'iac_count'],
      dtype='object')

### previous-click time

In [4]:
full_data = pd.read_csv('full_data_0702.csv')

In [5]:
full_data.shape

(118123128, 26)

In [11]:
fmt = '%Y-%m-%d %H:%M:%S'

In [8]:
current_time = pd.DataFrame(full_data['click_time'])

In [8]:
current_time.shape

(118123128, 1)

In [9]:
ido_pct = full_data[['day', 'ip', 'device', 'os', 'click_time']].groupby(['day', 'ip', 'device', 'os'])['click_time'].shift(+1)

In [10]:
ido_pct = np.where(ido_pct.isnull(), current_time['click_time'], ido_pct)

In [11]:
ido_pct = pd.DataFrame(ido_pct)
ido_pct.columns = ['pre_click_time']

In [12]:
ido_pct.shape

(118123128, 1)

In [13]:
# ido_pct.to_csv('ido_pct.csv', index = False)

In [14]:
# current_time.to_csv('current_time.csv', index = False)

In [15]:
# ido_pct = pd.read_csv('ido_pct.csv')

In [18]:
ido_pct = ido_pct['pre_click_time'].apply(lambda x: datetime.strptime(str(x), fmt))

In [6]:
current_time = pd.read_csv('current_time.csv')

In [15]:
current_time = current_time['click_time'].apply(lambda x: datetime.strptime(str(x), fmt))

In [20]:
full_data['ido_pct'] = current_time - ido_pct

In [28]:
pd.DataFrame(full_data['ido_pct']).to_csv('ido_diff.csv')

In [29]:
gc.collect()

97

In [30]:
full_data['ido_pct'] = full_data['ido_pct'].apply(lambda x: x.seconds)

In [33]:
full_data.head(100)

,ip,app,device,os,channel,click_time,day,weekday,hour,minutes,...,ipdevice_count,ipos_count,appdevice_count,appchannel_count,appos_count,ida_count,ido_count,ioc_count,iac_count,ido_pct
0,83230,3,1,13,379,2017-11-06 14:32:21,6,0,14,32,...,14945,3500,19293035,646698,4443880,2888,3473,46,101,0
1,17357,3,1,19,379,2017-11-06 14:33:34,6,0,14,33,...,14629,4107,19293035,646698,4793727,2725,4105,65,101,0
2,35810,3,1,13,379,2017-11-06 14:34:12,6,0,14,34,...,5639,1309,19293035,646698,4443880,1208,1084,16,28,0
3,45745,14,1,13,478,2017-11-06 14:34:52,6,0,14,34,...,102976,23845,6169877,11768,1366829,6425,20948,89,35,0
4,161007,3,1,13,379,2017-11-06 14:35:08,6,0,14,35,...,435,134,19293035,646698,4443880,82,134,5,3,0
5,18787,3,1,16,379,2017-11-06 14:36:26,6,0,14,36,...,2345,78,19293035,646698,337563,508,78,2,12,0
6,103022,3,1,23,379,2017-11-06 14:37:44,6,0,14,37,...,2960,2,19293035,646698,175367,562,2,1,31,0
7,114221,3,1,19,379,2017-11-06 14:37:59,6,0,14,37,...,1418,368,19293035,646698,4793727,225,368,12,9,0
8,165970,3,1,13,379,2017-11-06 14:38:10,6,0,14,38,...,1107,146,19293035,646698,4443880,242,83,1,4,0
9,74544,64,1,22,459,2017-11-06 14:38:23,6,0,14,38,...,2157,95,937280,959523,31145,12,95,1,12,0
10,172522,3,1,25,379,2017-11-06 14:38:27,6,0,14,38,...,2546,68,19293035,646698,450809,451,68,5,18,0
11,105861,3,1,13,379,2017-11-06 14:38:51,6,0,14,38,...,4923,1268,19293035,646698,4443880,817,1148,20,33,0
12,210962,3,1,19,379,2017-11-06 14:39:29,6,0,14,39,...,5351,1238,19293035,646698,4793727,721,1160,20,20,0
13,124979,3,1,18,379,2017-11-06 14:40:16,6,0,14,40,...,450,24,19293035,646698,1014043,67,24,1,3,0
14,38816,3,1,18,379,2017-11-06 14:40:39,6,0,14,40,...,2658,60,19293035,646698,1014043,452,60,1,18,0
15,80447,3,1,19,379,2017-11-06 14:40:51,6,0,14,40,...,2346,430,19293035,646698,4793727,464,430,14,18,0
16,134575,3,1,13,379,2017-11-06 14:43:10,6,0,14,43,...,1898,209,19293035,646698,4443880,133,208,4,2,0
17,57576,3,1,19,379,2017-11-06 14:43:14,6,0,14,43,...,258,127,19293035,646698,4793727,37,127,1,3,0
18,7755,3,1,13,379,2017-11-06 14:43:25,6,0,14,43,...,440,86,19293035,646698,4443880,65,67,3,9,0
19,91749,3,1,19,379,2017-11-06 14:43:51,6,0,14,43,...,3112,1243,19293035,646698,4793727,518,1102,16,11,0
20,50694,3,1,18,379,2017-11-06 14:44:02,6,0,14,44,...,692,66,19293035,646698,1014043,99,66,3,5,0
21,111385,3,1,18,379,2017-11-06 14:44:15,6,0,14,44,...,1355,20,19293035,646698,1014043,263,20,1,8,0
22,125222,14,1,3,478,2017-11-06 14:44:51,6,0,14,44,...,97354,2133,6169877,11768,101811,5950,1945,7,21,0
23,191759,3,1,13,379,2017-11-06 14:44:51,6,0,14,44,...,12456,3151,19293035,646698,4443880,2427,2932,94,77,0
24,53418,3,1,17,379,2017-11-06 14:44:52,6,0,14,44,...,1529,74,19293035,646698,1076772,242,74,3,8,0
25,183168,3,1,19,379,2017-11-06 14:47:49,6,0,14,47,...,15,19,19293035,646698,4793727,4,2,1,1,0
26,47902,3,1,17,379,2017-11-06 14:48:07,6,0,14,48,...,3032,248,19293035,646698,1076772,603,248,13,21,0
27,209663,3,1,13,379,2017-11-06 14:48:55,6,0,14,48,...,75189,16050,19293035,646698,4443880,9681,13634,119,191,0
28,129614,3,1,20,379,2017-11-06 14:49:36,6,0,14,49,...,572,9,19293035,646698,447554,99,9,1,6,0
29,208347,3,1,19,379,2017-11-06 14:49:38,6,0,14,49,...,1504,592,19293035,646698,4793727,71,592,2,4,0
30,73503,3,1,18,379,2017-11-06 14:49:43,6,0,14,49,...,820,11,19293035,646698,1014043,137,11,1,4,0
31,28739,3,1,13,379,2017-11-06 14:50:29,6,0,14,50,...,12131,2962,19293035,646698,4443880,2045,2730,56,89,0
32,206897,3,1,13,379,2017-11-06 14:51:52,6,0,14,51,...,1586,198,19293035,646698,4443880,221,198,8,9,0
33,30986,3,1,19,379,2017-11-06 14:52:13,6,0,14,52,...,3195,1048,19293035,646698,4793727,545,1048,19,18,0
34,2805,3,1,16,379,2017-11-06 14:52:58,6,0,14,52,...,15874,260,19293035,646698,337563,2883,244,10,92,0
35,103175,18,1,17,376,2017-11-06 14:53:23,6,0,14,53,...,1580,93,10103073,339787,544215,165,93,3,9,0
36,23550,3,1,13,379,2017-11-06 14:53:39,6,0,14,53,...,1776,351,19293035,646698,4443880,316,351,16,9,0
37,29045,64,1,13,459,2017-11-06 14:54:59,6,0,14,54,...,5121,1184,937280,959523,176843,40,989,16,48,0
38,74715,3,1,19,379,2017-11-06 14:55:25,6,0,14,55,...,764,279,19293035,646698,4793727,143,261,4,6,0
39,148454,3,1,19,379,2017-11-06 14:55:32,6,0,14,55,...,2551,567,19293035,646698,4793727,476,546,19,18,0
40,31529,3,1,15,379,2017-11-06 14:56:11,6,0,14,56,...,3150,137,19293035,646698,486306,489,137,5,16,0
41,16760,3,1,15,379,2017-11-06 14:56:12,6,0,14,56,...,1593,39,19293035,646698,486306,274,26,2,14,0
42,84644,3,1,19,379,2017-11-06 14:56:49,6,0,14,56,...,48200,11429,19293035,646698,4793727,7613,10869,368,253,0
43,121942,3,1,13,379,2017-11-06 14:57:33,6,0,14,57,...,8534,2263,19293035,646698,4443880,1499,1897,30,49,0
44,25236,3,1,18,379,2017-11-06 14:57:40,6,0,14,57,...,1580,110,19293035,646698,1014043,289,110,5,6,0
45,38036,3,1,19,379,2017-11-06 14:57:40,6,0,14,57,...,1346,297,19293035,646698,4793727,103,297,5,6,0
46,129614,3,1,19,379,2017-11-06 14:57:50,6,0,14,57,...,572,131,19293035,646698,4793727,99,124,4,6,0
47,128855,3,1,13,379,2017-11-06 14:58:16,6,0,14,58,...,1149,282,19293035,646698,4443880,187,282,12,8,0
48,166030,3,1,19,379,2017-11-06 15:02:51,6,0,15,2,...,1638,523,19293035,646698,4793727,303,523,14,11,0
49,166862,3,1,13,379,2017-11-06 15:02:52,6,0,15,2,...,294,62,19293035,646698,4443880,41,62,4,4,0
50,153492,3,1,17,379,2017-11-06 15:03:11,6,0,15,3,...,2885,140,19293035,646698,1076772,542,140,3,14,0
51,88150,3,1,13,379,2017-11-06 15:04:04,6,0,15,4,...,3481,829,19293035,646698,4443880,566,829,28,18,0
52,108942,3,1,19,379,2017-11-06 15:04:28,6,0,15,4,...,48773,13248,19293035,646698,4793727,7491,12693,350,321,0
53,55774,3,1,13,379,2017-11-06 15:05:05,6,0,15,5,...,10854,2289,19293035,646698,4443880,1669,1961,23,33,0
54,64886,3,1,13,379,2017-11-06 15:05:17,6,0,15,5,...,4256,1021,19293035,646698,4443880,649,1020,13,27,0
55,192796,3,1,19,379,2017-11-06 15:07:24,6,0,15,7,...,372,55,19293035,646698,4793727,54,54,2,2,0
56,32450,3,1,17,379,2017-11-06 15:07:29,6,0,15,7,...,2335,137,19293035,646698,1076772,462,92,3,18,0
57,38763,3,1,13,379,2017-11-06 15:08:04,6,0,15,8,...,2885,687,19293035,646698,4443880,559,687,17,18,0
58,90452,64,1,17,459,2017-11-06 15:08:11,6,0,15,8,...,1225,57,937280,959523,47257,20,57,5,20,0
59,147605,3,1,19,379,2017-11-06 15:08:24,6,0,15,8,...,3151,854,19293035,646698,4793727,559,854,27,20,0
60,38683,3,1,19,379,2017-11-06 15:08:26,6,0,15,8,...,720,240,19293035,646698,4793727,138,240,6,6,0
61,199564,3,1,13,379,2017-11-06 15:09:44,6,0,15,9,...,678,143,19293035,646698,4443880,135,127,5,12,0
62,1025,3,1,17,379,2017-11-06 15:10:55,6,0,15,10,...,7789,439,19293035,646698,1076772,1185,381,7,55,0
63,61678,3,1,18,379,2017-11-06 15:11:15,6,0,15,11,...,882,12,19293035,646698,1014043,132,12,1,5,0
64,107899,6,1,13,459,2017-11-06 15:12:43,6,0,15,12,...,8507,2156,1536704,1049171,373088,144,1973,72,125,0
65,89489,3,1,13,379,2017-11-06 15:13:23,6,0,15,13,...,4275,1123,19293035,646698,4443880,753,1117,36,35,0
66,33195,3,1,13,379,2017-11-06 15:13:42,6,0,15,13,...,1631,177,19293035,646698,4443880,130,177,6,5,0
67,164537,58,1,19,120,2017-11-06 15:14:35,6,0,15,14,...,1,1,27429,28876,6164,1,1,1,1,0
68,36213,64,1,22,459,2017-11-06 15:14:48,6,0,15,14,...,52097,2260,937280,959523,31145,397,1931,18,405,0
69,6242,3,1,17,379,2017-11-06 15:15:52,6,0,15,15,...,2353,280,19293035,646698,1076772,466,280,8,16,0
70,129614,3,1,15,379,2017-11-06 15:16:47,6,0,15,16,...,572,9,19293035,646698,486306,99,9,1,6,0
71,123722,3,1,18,379,2017-11-06 15:18:58,6,0,15,18,...,1928,23,19293035,646698,1014043,350,23,1,16,0
72,158417,3,1,13,379,2017-11-06 15:19:19,6,0,15,19,...,2888,459,19293035,646698,4443880,501,407,11,23,0
73,78349,3,1,13,379,2017-11-06 15:20:03,6,0,15,20,...,775,208,19293035,646698,4443880,113,191,7,17,0
74,89489,3,1,13,379,2017-11-06 15:20:38,6,0,15,20,...,4275,1123,19293035,646698,4443880,753,1117,36,35,435
75,99641,64,1,10,459,2017-11-06 15:21:24,6,0,15,21,...,2758,46,937280,959523,28167,34,46,3,34,0
76,3653,3,1,18,379,2017-11-06 15:21:34,6,0,15,21,...,1336,30,19293035,646698,1014043,256,30,1,9,0
77,209663,3,1,19,379,2017-11-06 15:22:08,6,0,15,22,...,75189,19754,19293035,646698,4793727,9681,17946,153,191,0
78,88075,3,1,19,379,2017-11-06 15:24:03,6,0,15,24,...,1836,200,19293035,646698,4793727,306,200,10,8,0
79,108881,3,1,19,379,2017-11-06 15:25:15,6,0,15,25,...,55289,15061,19293035,646698,4793727,8553,14503,429,363,0
80,82650,3,1,25,379,2017-11-06 15:25:32,6,0,15,25,...,2224,67,19293035,646698,450809,432,67,3,15,0
81,172483,3,1,13,379,2017-11-06 15:26:02,6,0,15,26,...,2719,682,19293035,646698,4443880,435,663,21,14,0
82,191894,3,1,18,379,2017-11-06 15:29:16,6,0,15,29,...,9090,422,19293035,646698,1014043,1768,395,10,57,0
83,109591,3,1,19,379,2017-11-06 15:30:16,6,0,15,30,...,732,180,19293035,646698,4793727,124,180,6,6,0
84,3425,3,1,17,379,2017-11-06 15:31:48,6,0,15,31,...,937,64,19293035,646698,1076772,133,64,3,7,0
85,72078,3,1,19,379,2017-11-06 15:33:52,6,0,15,33,...,2849,663,19293035,646698,4793727,543,663,8,12,0
86,100224,3,1,13,379,2017-11-06 15:36:40,6,0,15,36,...,1536,273,19293035,646698,4443880,269,273,12,13,0
87,197717,3,1,19,379,2017-11-06 15:37:18,6,0,15,37,...,845,261,19293035,646698,4793727,128,261,1,4,0
88,108942,3,1,13,379,2017-11-06 15:37:28,6,0,15,37,...,48773,11283,19293035,646698,4443880,7491,10370,330,321,0
89,203397,3,1,19,379,2017-11-06 15:38:24,6,0,15,38,...,1886,464,19293035,646698,4793727,392,464,14,10,0
90,109591,3,1,19,379,2017-11-06 15:39:16,6,0,15,39,...,732,180,19293035,646698,4793727,124,180,6,6,540
91,116013,3,1,13,379,2017-11-06 15:39:18,6,0,15,39,...,2704,561,19293035,646698,4443880,365,561,9,11,0
92,42102,3,1,13,379,2017-11-06 15:39:47,6,0,15,39,...,2154,555,19293035,646698,4443880,379,554,11,15,0
93,110980,64,1,49,459,2017-11-06 15:40:30,6,0,15,40,...,4536,7,937280,959523,11710,29,7,1,29,0
94,41981,3,1,13,379,2017-11-06 15:40:32,6,0,15,40,...,2356,558,19293035,646698,4443880,512,515,19,23,0
95,44932,3,1,19,379,2017-11-06 15:40:33,6,0,15,40,...,2593,1126,19293035,646698,4793727,487,1126,17,15,0
96,63839,3,1,19,379,2017-11-06 15:40:37,6,0,15,40,...,2474,658,19293035,646698,4793727,435,657,10,15,0
97,62129,3,1,19,379,2017-11-06 15:40:40,6,0,15,40,...,24229,6630,19293035,646698,4793727,3118,6259,122,152,0
98,199328,64,1,22,459,2017-11-06 15:40:41,6,0,15,40,...,235,11,937280,959523,31145,3,11,1,3,0
99,127226,3,1,13,379,2017-11-06 15:40:56,6,0,15,40,...,154,57,19293035,646698,4443880,37,57,3,4,0

In [34]:
full_data.to_csv('full_data_0702_version2.csv')

In [3]:
full_data = pd.read_csv('full_data_0702_version2.csv', index_col = 0)

/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:472: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [4]:
didoa_pct = full_data[['day', 'ip', 'device', 'os', 'app', 'click_time']].groupby(['day', 'ip', 'device', 'os', 'app'])['click_time'].shift(+1)

In [9]:
didoa_pct = np.where(didoa_pct.isnull(), current_time['click_time'], didoa_pct)

In [10]:
didoa_pct = pd.DataFrame(didoa_pct)
didoa_pct.columns = ['didoa_pre_click_time']

In [13]:
didoa_pct = didoa_pct['didoa_pre_click_time'].apply(lambda x: datetime.strptime(str(x), fmt))

In [16]:
full_data['didoa_pct'] = current_time - didoa_pct

In [18]:
full_data['didoa_pct'] = full_data['didoa_pct'].apply(lambda x: x.seconds)

In [17]:
gc.collect()

14

In [21]:
full_data.shape

(118123128, 28)

In [22]:
full_data.to_csv('full_data_0702.csv')

In [23]:
full_data.shape

(118123128, 28)

### unique feature

nunique-count feature
* ip [app]
* ip [device]
* ip [os]
* ip [channel]
* app [os]
* app [channel]
* ip, app [os]
* ip, app [device]
* ip, device, os [app]
* ip, day [hour]

In [3]:
full_data = pd.read_csv('full_data_0702.csv')

In [4]:
full_data.shape

(118123128, 26)

In [5]:
full_data = full_data[full_data.hour != 12]

In [6]:
full_data.shape

(108273763, 26)

In [10]:
del t

In [13]:
def count_nunique(groupby_col, n_col, newname, filename):
    ncol_count = pd.DataFrame(full_data[groupby_col + [n_col]].groupby(groupby_col)[n_col].nunique()).reset_index()
    ncol_count.rename(columns={n_col: newname}, inplace = True)
    ncol_count.to_csv(filename, index = False)
    return ncol_count

In [14]:
napp_byip = count_nunique(['ip'], 'app', 'napp_byip', 'napp_byip.csv')

In [16]:
ndevice_byip = count_nunique(['ip'], 'device', 'ndevice_byip', 'ndevice_byip.csv')

In [17]:
nos_byip = count_nunique(['ip'], 'os', 'nos_byip', 'nos_byip.csv')

In [18]:
nchannel_byip = count_nunique(['ip'], 'channel', 'nchannel_byip', 'nchannel_byip.csv')

In [26]:
nunique_byip = pd.merge(napp_byip, ndevice_byip, on = ['ip'])
nunique_byip = nunique_byip.merge(nos_byip, on = ['ip'])
nunique_byip = nunique_byip.merge(nchannel_byip, on = ['ip'])

In [29]:
nunique_byip.to_csv('nunique_byip.csv', index = False)

In [30]:
nos_byapp = count_nunique(['app'], 'os', 'nos_byapp', 'nos_byapp.csv')

In [31]:
nchannel_byapp = count_nunique(['app'], 'channel', 'nchannel_byapp', 'nchannel_byapp.csv')

In [32]:
nos_byapp.shape

(643, 2)

In [35]:
nunique_byapp = pd.merge(nos_byapp, nchannel_byapp, on = ['app'])

In [37]:
nunique_byapp.to_csv('nunique_byapp.csv', index = False)

In [38]:
nos_byipapp = count_nunique(['ip', 'app'], 'os', 'nos_byipapp', 'nos_byipapp.csv')

In [39]:
ndevice_byipapp = count_nunique(['ip', 'app'], 'device', 'ndevice_byipapp', 'ndevice_byipapp.csv')

In [42]:
nunique_byipapp = pd.merge(nos_byipapp, ndevice_byipapp, on = ['ip', 'app'])

In [43]:
nunique_byipapp.to_csv('nunique_byipapp.csv')

In [44]:
napp_byido = count_nunique(['ip', 'device', 'os'], 'app', 'napp_byido', 'napp_byido.csv')

In [45]:
nhour_byipday = count_nunique(['ip', 'day'], 'hour', 'nhour_byipday', 'nhour_byipday.csv')

In [2]:
full_data = pd.read_csv('full_data_0702.csv', index_col = 0)

/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:472: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [3]:
nunique_byip = pd.read_csv('nunique_byip.csv', index_col = 0)

In [4]:
nunique_byapp = pd.read_csv('nunique_byapp.csv', index_col = 0)

In [6]:
# full_data = pd.merge(full_data, nunique_byip, on = ['ip'], how = 'left')

In [4]:
ip = pd.DataFrame(full_data['ip'])
ip.head()

       ip
0   83230
1   17357
2   35810
3   45745
4  161007

In [5]:
nunique_ip_df = pd.merge(ip, nunique_byip, on = 'ip', how = 'left')

In [7]:
nunique_ip_df.head()

       ip  napp_byip  ndevice_byip  nos_byip  nchannel_byip
0   83230       64.0          18.0      58.0          112.0
1   17357       61.0          15.0      62.0          114.0
2   35810       56.0          14.0      67.0          132.0
3   45745      128.0          76.0     101.0          125.0
4  161007       32.0           4.0      25.0           74.0

In [8]:
full_data['napp_byip'] = nunique_ip_df['napp_byip']

In [9]:
full_data['ndevice_byip'] = nunique_ip_df['ndevice_byip']

In [10]:
full_data['nos_byip'] = nunique_ip_df['nos_byip']

In [11]:
full_data['nchannel_byip'] = nunique_ip_df['nchannel_byip']

In [12]:
full_data.to_csv('full_data_0702_version2.csv')

In [13]:
full_data[' ']

,ip,app,device,os,channel,click_time,day,weekday,hour,minutes,...,ida_count,ido_count,ioc_count,iac_count,ido_pct,didoa_pct,napp_byip,ndevice_byip,nos_byip,nchannel_byip
0,83230,3,1,13,379,2017-11-06 14:32:21,6,0,14,32,...,2888,3473,46,101,0,0,64.0,18.0,58.0,112.0
1,17357,3,1,19,379,2017-11-06 14:33:34,6,0,14,33,...,2725,4105,65,101,0,0,61.0,15.0,62.0,114.0
2,35810,3,1,13,379,2017-11-06 14:34:12,6,0,14,34,...,1208,1084,16,28,0,0,56.0,14.0,67.0,132.0
3,45745,14,1,13,478,2017-11-06 14:34:52,6,0,14,34,...,6425,20948,89,35,0,0,128.0,76.0,101.0,125.0
4,161007,3,1,13,379,2017-11-06 14:35:08,6,0,14,35,...,82,134,5,3,0,0,32.0,4.0,25.0,74.0

In [14]:
full_data.shape

(118123128, 32)

The history saving thread hit an unexpected error (OperationalError('unable to open database file',)).History will not be written to the database.